BEGIN TRANSACTION;
DROP TABLE IF EXISTS `List`;
CREATE TABLE IF NOT EXISTS `List` (
	`Id`	INTEGER NOT NULL,
	`start`	NUMERIC NOT NULL,
	`end`	NUMERIC NOT NULL,
	`period`	NUMERIC NOT NULL
);
INSERT INTO `List` (Id,start,end,period) VALUES (0,8,18,0),
 (1,12,15,0);
COMMIT;
